name: build-image

on:
  push:
    branches: master

  schedule:
    - cron: '0 0 * * 0' # weekly at midnight on sunday

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set date
        id: date
        run: |
          echo ::set-output name=date::$(date -u +'%Y-%m-%d')

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args:
          - PYENV_EXTRA_PYTHON_VERSIONS=3.4.2 3.5.7 3.6.8 3.7.3
          - PYENV_UPDATED_AT=${{ steps.date.outputs.date }}
          pull: true
          push: true
          tags: randomknowledge/docker-pyenv-tox:latest

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
